name: Caching with guix
on: push
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Cache guix
        id: cache-guix
        uses: actions/cache@v3
        env:
          cache-name: cache-guix
        with:
          path: |
                /gnu
                /etc/guix
                /var/guix
                ~/.cache/guix
                /root/.config/guix
                /etc/group
                /etc/group-
                /etc/shadow
                /etc/systemd/system/guix-daemon.service.wants/gnu-store.mount
                /etc/systemd/system/guix-daemon.service.wants/gnu-daemon.mount
                /etc/systemd/system/guix-store.mount
                /etc/systemd/system/guix-daemon.service
          key: guix-cache-${{ github.sha }}
          restore-keys: |
            guix-cache-
      - if: ${{ steps.cache-guix.outputs.cache-hit != 'true' }}
        run: |
          wget -nv https://git.savannah.gnu.org/cgit/guix.git/plain/etc/guix-install.sh -O guix-install.sh
        name: Download
      - if: ${{ steps.cache-guix.outputs.cache-hit != 'true' }}
        run: |
          wget "https://savannah.gnu.org/people/viewgpg.php?user_id=127547" -qO - | sudo gpg --import -
          wget "https://savannah.gnu.org/people/viewgpg.php?user_id=15145" -qO - | sudo gpg --import -
        name: Fetch key
      - if: ${{ steps.cache-guix.outputs.cache-hit != 'true' }}
        run: |
          sudo -- bash -c 'yes | bash guix-install.sh'; echo 'ok'
        name: Install Guix

      - run: |
          sudo systemctl daemon-reload
          sudo systemctl restart guix-daemon
      - name: build
        run: guix build hello