name: Caching with guix
on: push
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Cache guix
        id: cache-guix
        uses: divnix/nix-cache-action@v3.0.11-nix
        env:
          cache-name: cache-guix
        with:
          path: |
                /gnu
                /etc/guix
                /var/guix
                ~/.cache/guix
                ~root/.cache/guix
                /etc/group
                /etc/group-
                /etc/shadow
                /etc/systemd/system/guix-store.mount
                /etc/systemd/system/guix-daemon.service
          key: guix-cache-${{ github.sha }}
          restore-keys: |
            guix-cache-
      - name: Install Guix
        if: steps.cache-guix.outputs.cache-hit != 'true'
        id: install-guix
        uses: PromyLOPh/guix-install-action@v1

      - run: |
          sudo systemctl daemon-reload
          sudo systemctl enable --now guix-daemon
      - name: build
        run: guix build hello